- name: Set Prompt
  ansible.builtin.shell: set-prompt jenkins-ci-agent

- name: Install Java
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
    state: installed

- name: Add Jenkins user
  ansible.builtin.user:
    name: jenkins
    home: /jenkins

- name: Download Agent Jar file
  ansible.builtin.get_url:
    url: http://{{secrets.user}}:{{secrets.password}}@jenkins-internal.rdevopsb79.online:8080/jnlpJars/agent.jar
    dest: /jenkins/agent.jar
  become_user: jenkins

- name: Disable TMPFS
  ansible.builtin.shell: |
    systemctl mask tmp.mount
    df | grep ^tmpfs | grep /tmp && umount /tmp || true

- name: Copy Jenkins Service file
  ansible.builtin.template:
    src: jenkins-ci-agent.service
    dest: /etc/systemd/system/jenkins-ci-agent.service

- name: Start Agent Service
  ansible.builtin.systemd_service:
    name: jenkins-ci-agent
    state: restarted
    enabled: yes
    daemon-reload: yes


## CI Related tools
- name: Install Maven
  ansible.builtin.unarchive:
    src: "https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip"
    dest: /opt
    remote_src: true


- name: Download and extract sonar-scanner
  ansible.builtin.unarchive:
    remote_src: true
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
    dest: /opt
    owner: jenkins
    group: jenkins

- name: Download Hashicorp repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Hashicorp Vault
  ansible.builtin.dnf:
    name: vault
    state: installed









