- name: Set Prompt
  ansible.builtin.shell: set-prompt jenkins-ci-agent

- name: Install Java
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
    state: installed

- name: Download Agent Jar file
  ansible.builtin.get_url:
    url: http://{{secrets.user}}:{{secrets.password}}@jenkins.rdevopsb79.online:9090/jnlpJars/agent.jar
    dest: /home/ec2-user/remoting.jar
  become_user: ec2-user









