- name: Set Prompt
  ansible.builtin.shell: set-prompt ci-server

- name: Copy Jenkins repo file
  ansible.builtin.copy:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
      - jenkins
    state: installed

- name: Create groovy init directory
  ansible.builtin.file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins

- name: Copy groovy files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /var/lib/jenkins/init.groovy.d/{{ item }}
    owner: jenkins
    group: jenkins
  loop:
    - 01-wizard.groovy


- name: Start Jenkins Service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: yes









